# Generated by Django 5.1.4 on 2025-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='entry',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
