# Generated by Django 5.1.4 on 2025-01-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedb', '0002_pokemon_description_pokemon_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='images',
            field=models.TextField(default=''),
        ),
    ]
